/**
 * @file    S2LP_CORE_SPI.h
 * @author  ST Microelectronics
 * @brief   Legacy include file to let S2LP Library compile
 * @details
 *
 * THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS
 * WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE
 * TIME. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY
 * DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING
 * FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE
 * CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
 *
 * THIS SOURCE CODE IS PROTECTED BY A LICENSE.
 * FOR MORE INFORMATION PLEASE CAREFULLY READ THE LICENSE AGREEMENT FILE LOCATED
 * IN THE ROOT DIRECTORY OF THIS FIRMWARE PACKAGE.
 *
 * <h2><center>&copy; COPYRIGHT 2021 STMicroelectronics</center></h2>
 */

#ifndef __S2LP_CORE_SPI_H__
#define __S2LP_CORE_SPI_H__

#include "s2lp.h"

#define		S2LPSpiReadRegisters(...)       S2LP_ReadRegister(__VA_ARGS__)
#define		S2LPSpiWriteRegisters(...)      S2LP_WriteRegister(__VA_ARGS__)
#define     S2LPSpiWriteFifo(...)           S2LP_WriteFIFO(__VA_ARGS__)
#define     S2LPSpiReadFifo(...)            S2LP_ReadFIFO(__VA_ARGS__)
#define     S2LPSpiCommandStrobes(...)      S2LP_SendCommand(__VA_ARGS__)

#endif /*__S2LP_CORE_SPI_H__*/
